### PR TITLE
ZMX protocol parser rework

### LINKED ISSUE #9: Separate RESP protocol and ZMX protocol
RESP protocol is just about serialization and could be implemented separately from ZMX protocol. Where ZMX protocol would be just a specific set of commands on top of RESP.

### LINKED ISSUE #76: Server fails when handling a bad RESP request
When issued a bad bulk string command the ZMX server fails and doesn't respond to subsequent requests.

Example bad request (wrong char number):
```
echo -ne '*1\r\n$3\r\ndump\r\n' | nc localhost 1111
```
should be:
```
echo -ne '*1\r\n$4\r\ndump\r\n' | nc localhost 1111
```

### PR DESCRIPTION
**Pull request by lkff**
Follow up to #125.

 * Update examples and clarify few things in `diagnostics.md`
 * Remove `ZMXParser` related files as these will be replaced with bunch of static methods (part two of #110 issue)
 * Add `Parser` for handling `ZMXProtocol` parsing/serialization using recently added RESP implementation
 * Add `ParserSpec` with tests for `Parser`
 * Simplify `ZMXClient` implementation by reusing recent RESP implementation
 * Update `ZMXClientSpec` to match `ZMXClient` changes
 * Improve `ZMXProtocol` with new helper `Command.fromString` method and new error type of `InvalidRequest`
 * Update `ZMXServer` after `ZMXParser` deletion
 * Update `zio/package.scala` after `ZMXParser` deletion, also format and sort imports

Closes #9. 
Fixes #76.

### CODE REVIEW

**Review by adamgfraser — APPROVED** [review]
Amazing!

**Comment by lkff** [comment]
Regarding fixing #76, here's a proof 😉 

image

Now ZMX server responds with a proper error message.

File: src/main/scala/zio/zmx/diagnostics/parser/Parser.scala [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+        case ZMXProtocol.Error.MalformedRequest(error) => Resp.Error(s"MALFORMED REQUEST: `$error`!").serialize
+        case ZMXProtocol.Error.UnknownCommand(command) => Resp.Error(s"UNKNOWN COMMAND: `$command`!").serialize
+      }
+
+    case ZMXProtocol.Response.Success(data) =>
+      data match {
+        case executionMetrics: ZMXProtocol.Data.ExecutionMetrics =>
+          // TODO: Format of `ExecutionMetrics` serialized could be discussed and revisited.
+          Resp.BulkString(executionMetrics.toString).serialize
+
```
Comment (lkff) [inline src/main/scala/zio/zmx/diagnostics/parser/Parser.scala:84]: Regarding this, I will create an issue soon.
I think we can improve current format with recently added proper RESP implementation.

Right now whole metrics are a single Bulk String, eg.:
```
$86\r\n
concurrency:1\r\n
capacity:2\r\n
size:3\r\n
enqueued_count:4\r\n
dequeued_count:5\r\n
workers_count:6\r\n
```

Didn't want to break the current approach in this PR but I think it makes sense to use an Array here.
Actually the `key:value` pairs can be Arrays themselves as well.
